# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tictactoe.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import random,sys
import socket , threading, json
class Ui_MainWindow(QtWidgets.QMainWindow):
    combinations = [
            [1,2,3],[4,5,6],[7,8,9],
            [1,4,7],[2,5,8],[3,6,9],
            [1,5,9],[3,5,7]
    ]    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 484)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 100, 361, 31))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 581, 391))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 441, 371))
        self.label_3.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/tictactoe.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 30, 111, 86))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 140, 111, 86))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 260, 111, 86))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(166, 260, 111, 86))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(166, 140, 111, 86))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(166, 30, 111, 86))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QtCore.QRect(301, 260, 111, 86))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setGeometry(QtCore.QRect(301, 30, 111, 86))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QtCore.QRect(301, 140, 111, 86))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_10.setAutoDefault(False)
        self.pushButton_10.setDefault(False)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")
        
        # self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        # self.pushButton_11.setGeometry(QtCore.QRect(470, 240, 101, 23))
        # self.pushButton_11.setObjectName("pushButton_11")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "4"))
        self.pushButton_4.setText(_translate("MainWindow", "7"))
        self.pushButton_5.setText(_translate("MainWindow", "8"))
        self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "2"))
        self.pushButton_8.setText(_translate("MainWindow", "9"))
        self.pushButton_9.setText(_translate("MainWindow", "3"))
        self.pushButton_10.setText(_translate("MainWindow", "6"))
        
        # self.pushButton_11.setText(_translate("MainWindow", "RESET BUTTON"))
        self.frame.hide()

        self.initEvents()

    def initEvents(self):

        self.frame.show()

        
        self.btns  = [self.pushButton_2,self.pushButton_7,self.pushButton_9,
                  self.pushButton_3,self.pushButton_6,self.pushButton_10,
                  self.pushButton_4,self.pushButton_5,self.pushButton_8]
        threading.Thread(target=self.check).start()
        # self.pushButton_11.clicked.connect(self.Restart)
        for i in range(len(self.btns)) :
            self.btns[i].clicked.connect(self.user_move)




    def user_move(self):
        try:
            btn = self.sender()
            self.pos=int(btn.text())
            btn.setDisabled(True)
            btn.setText(self.client_ch)
            self.winner(self.pos,self.client_ch)
            self.sendPosition(self.pos)
        except BaseException as ex:
            print(ex)
    
    def setServerPosition(self,pos,ch):
            btn = self.btns[pos-1]
            self.pos=int(btn.text())
            btn.setDisabled(True)
            btn.setText(self.server_ch)
            self.winner(self.pos,self.server_ch)
        
    def sendPosition(self,pos):
        msg = {"pos":pos}
        msg = json.dumps(msg)
        self.s.send(msg.encode())
    
    def winner(self,pos,ch):
        for i in range(len(self.combinations)):
            if pos in self.combinations[i]:
                index=self.combinations[i].index(pos)
                self.combinations[i][index] = ch


        for i in range(len(self.combinations)):
            if self.combinations[i][0]==ch and self.combinations[i][1]==ch and self.combinations[i][2]==ch:
                    QMessageBox.about(self,"Game Over","Client win".format(ch))


    def check(self):
        self.s = socket.socket()
        self.port= 9999
        self.s.connect(('localhost',self.port))
        while True:
           recv_msg=self.s.recv(1024).decode()
           print(f"Server : {recv_msg}")
           recv_msg  = json.loads(recv_msg)
           self.serverPos = recv_msg["pos"]
           self.client_ch = recv_msg['client_ch']
           self.server_ch = recv_msg['Server_ch']
           self.setServerPosition(self.serverPos,self.server_ch)           
                      

           
           
   
if __name__ == "__main__":
    import sys
    current_exit_code=1207
    while current_exit_code==1207: 
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        
        current_exit_code = sys.exit(app.exec_())
        
        ui=None
